#include <iostream>
#include <vector>
#define myout(msg,x)  cout<< "\n" << msg << ":"; for(auto s : x) cout << " " << s ;
using namespace std;

/* vector는 실제 3개의 pointer로 구성되어 있다. 따라서 크기는 4*3= 12 byte
   pointer    __begin_;
   pointer    __end_;
    __compressed_pair<pointer, allocator_type> __end_cap

   v.size() returns the number of elements in the vector.
   sizeof(v) gives the number of bytes used by the object definition,
   excluding any additional storage it has allocated through the use of pointers.
   It is a static constant generated by the compiler at compile time,
   based on the declaration of the vector class. */

int main() {
    vector <int> va ;
    vector <int> vb { 11, 22, 33, 44, 55, 66 };
    vector <double> vd ;
    list   <int> la ( { 9, 10, 11 } );
    set    <int> sa {0,1};
    deque  <int> da {1, 4};
    stack  <int> ta ;
    queue  <int> qa ;

    cout << "\n sizeof( char )= "      << sizeof(char)   ;
    cout << "\n sizeof( string )= "    << sizeof(string)   ;
    cout << "\n sizeof( int )= "       << sizeof(int)  ;
    cout << "\n sizeof( float )= "     << sizeof(float)  ;
    cout << "\n sizeof( long )= "      << sizeof(long)   ;
    cout << "\n sizeof( long long )= " << sizeof(long long)   ;
    cout << "\n sizeof( float )= "     << sizeof(float)   ;
    cout << "\n sizeof( double )= "    << sizeof(double) << endl  ;

    cout << "\n sizeof(va)= "  << sizeof(va) ;
    cout << "\n sizeof(la)= "  << sizeof(la) ;
    cout << "\n sizeof(vb)= "  << sizeof(vb) ;
    cout << "\n sizeof(vd)= "  << sizeof(vd) ;
    cout << "\n sizeof(va)= "  << sizeof(va) ;
    cout << "\n sizeof(la)= "  << sizeof(la) ;
    cout << "\n sizeof(da)= "  << sizeof(da) ;
    cout << "\n sizeof(ta)= "  << sizeof(la) ;
    cout << "\n sizeof(qa)= "  << sizeof(da)  << endl  ;

    cout << "\n va.size( )= "  << va.size( ) ;
    cout << "\n vb.size( )= "  << vb.size( ) ;
    cout << "\n vd.size( )= "  << vd.size( ) ;
    cout << "\n la.size( )= "  << la.size( ) ;
    cout << "\n sa.size( )= "  << sa.size( ) ;
    cout << "\n vd.size( )= "  << vd.size( ) ;
    cout << "\n ta.size( )= "  << ta.size( ) ;
    cout << "\n qa.size( )= "  << qa.size( ) ;

} // end of main( )
